# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci_renesas" "xhci_pci" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/64d3239d-1068-47cf-abc5-4478d57c7b6c";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/EBFD-8958";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  ###############################################################################################

  # 1. Включаем поддержку Bluetooth на уровне ядра и системы
  hardware.bluetooth.enable = true;
  hardware.bluetooth.powerOnBoot = true; # Чтобы не включать вручную каждый раз

  # 2. Включаем менеджер Blueman
  services.blueman.enable = true;

  # 3. (Опционально) Если хочешь, чтобы иконка была в трее Xfce
  environment.systemPackages = with pkgs; [
    xfce.xfce4-pulseaudio-plugin # Хорошо работает в паре с Bluetooth для звука
  ];

}
