[core]
plugins = alpha animate autostart command cube expo fire \
          grid move place resize vswitch window-rules \
          wm-actions wrot zoom wobbly
close_top_view = <super> KEY_Q

[animate]
close_animation = fire
duration = 400

[wobbly]
friction = 3.0
spring_constraint = 20.0

[cube]
activate = <super> <alt> BTN_LEFT

[autostart]
panel = wf-panel
background = wf-background

[command]
# Запуск терминала
binding_terminal = <ctrl> <alt> KEY_T
command_terminal = foot

# Запуск лаунчера приложений
binding_launcher = <super> KEY_D
command_launcher = fuzzel

# Скриншот выбранной области (сохраняет в Pictures)
binding_screenshot = KEY_PRINT
command_screenshot = grim -g "$(slurp)" ~/Pictures/$(date +%Y-%m-%d_%H-%m-%s).png

